# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# generated using file ./gen/model/linux/protocol/dnsmasq/dnsmasq.yaml
#
# DONOT EDIT - generated by diligent bots

from dent_os_testbed.lib.test_lib_object import TestLibObject


class LinuxDnsmasq(TestLibObject):
    """
    dnsmasq is a lightweight DNS, TFTP, PXE, router advertisement and DHCP server.
    It is intended to provide coupled DNS and DHCP service to a LAN.
    dnsmasq [OPTION]...

    """

    def format_test(self, command, *argv, **kwarg):
        raise NotImplementedError

    def parse_test(self, command, output, *argv, **kwarg):
        raise NotImplementedError

    def format_command(self, command, *argv, **kwarg):
        if command in ["test"]:
            return self.format_test(command, *argv, **kwarg)

        raise NameError("Cannot find command " + command)

    def parse_output(self, command, output, *argv, **kwarg):
        if command in ["test"]:
            return self.parse_test(command, output, *argv, **kwarg)

        raise NameError("Cannot find command " + command)
