"""
This file is not for editing.
These settings are configured in user's host server under /home/dent/DentCiMgmt/settings.sh
Please do not edit this file.
"""
import os
import sys
from dotenv import load_dotenv

currentDir = os.path.abspath(os.path.dirname(__file__))

if os.path.exists('/home/dent/DentCiMgmt/settings.sh') is False:
    sys.exit('You need to prime you Dent CI test server with a /home/dent/DentCiMgmt directory and copy the settings.sh file to this directory.  Please read the Readme and installation file')
else:
    load_dotenv('/home/dent/DentCiMgmt/settings.sh')

#    The IP address of your server to use
serverIpAddress: str = os.environ.get('DENT_SERVER_IP_ADDRESS', None)

# The prefix path to put the /CI_Automation folder
# This is where test results and many other framework management folder will reside
# Ex: /home/dent
baseDir = os.environ.get('DENT_BASE_DIR', '/home/dent')

#  CRUCIAL!
#     The static mac address for dhcp IP address
#     We need the IxNetworkVM to always have the same IP address
#     The DHCP server should have configured to listen for this Mac Address
#     and provide a persistent IP address
#     When the Dent CI framework brings up the IxNetworkVM docker container,
#     it includes this made-up mac address
ixNetworkVMDhcpMacAddress: str = os.environ.get('DENT_IxNETWORK_VM_DHCP_MAC_ADDRESS', None)

# Self-cleanup: How many days to keep test results.
# Example: 1 means to keep today and delete yesterday and beyond
#          2 means to keep last two days (today and yesterday) and delete everything else
removeTestResultsAfterNumberOfDays: int = int(os.environ.get('DENT_REMOVE_PAST_RESULTS_AFTER_DAYS=10', 10))

# Where to download builds from
downloadBuildUrlPrefixPath: str = os.environ.get('DENT_DOWNLOAD_BUILD_URL', None)

# The IxNetwork VM to download/install for running test
ixNetworkVMImage: str = os.environ.get('DENT_IXNETWORK_VM_IMAGE', None)

# Pull from this main repo as default if user did not specify a repo
gitCloneDefaultRepo:      str = 'https://github.com/dentproject/testing.git'

# Where is the Linux host server tftp default location
tftpServerFolder:         str = '/srv/tftp'
tftpServerPath:           str = f'tftp://{serverIpAddress}/{tftpServerFolder}'

# Where NGINX is configured as the nginx location to store dentOS image downloads
httpServerFolder:         str = os.environ.get('DENT_HTTP_SERVER_BUILDS_FOLDER', '/DentBuildReleases')
httpServerPath:           str = f'http://{serverIpAddress}{httpServerFolder}'

# /home/dent/testing/tools
dentToolsPath:            str = f'{os.environ.get("DENT_BASE_DIR", "/home/dent")}/testing/tools'

# /home/dent/testing/CI_Automation
dentCiFrameworkPath:      str = os.environ.get('DENT_CI_FRAMEWORK_PATH', '/home/dent/testing/CI_Automation')

# Used by runDentCi.py and ciUtils.py
# Ex: baseDir=/home/dent
dentCiMgmtPath:           str = f'{baseDir}/DentCiMgmt'

# Where to put all test session results and logs
# This is used by runDentCi.py and ciUtils.py
# /home/dent/DentCI/DentTestResults
dentTestResultsFolder:    str = f'{dentCiMgmtPath}/TestResults'

# Used by runDentCi.py and ciUtils.py
testbedMgmtFolder:        str = f'{dentCiMgmtPath}/TestbedMgmt'
testbedMgmtWaitingFolder: str = f'{testbedMgmtFolder}/Waiting'
disableSystemFilename:    str = 'disabledCiSystem'
