failure-threshold: warning
ignored:
- DL3007 # Using latest is prone to errors if the image will ever update. Pin the version explicitly to a release tag
- DL3008 # Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
- DL3009 # Delete the apt-get lists after installing something
- DL3015 # Avoid additional packages by specifying `--no-install-recommends`
- DL3059 # Multiple consecutive `RUN` instructions. Consider consolidation.
dockerfile: Dockerfile*
