# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-case-conflict
  - id: check-ast
  - id: check-json
  - id: double-quote-string-fixer
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: ["--max-line-length=201", "--extend-ignore=W605,F401,F402,F523,F524,F541,F601,F632,F811,F821,F841,E701,E722,E741,E203,E231,E122,E251"]
