- module: os
  description: os level information
  classes:
   - name: service
     desc: service related inforamtion
     apis: [ 'show' ]
     members:
      - name: name
        type: string
        desc: "The service name"
        key: True
      - name: loaded
        type: string
        desc: "if the modules is loaded"
      - name: active
        type: string
        desc: "is active"
      - name: status
        type: string
        desc: "check the status"
      - name: description
        type: string
        desc: "service description"
