###################################################################################
#	Marvell GPL License
#	
#	If you received this File from Marvell, you may opt to use, redistribute and/or
#	modify this File in accordance with the terms and conditions of the General
#	Public License Version 2, June 1991 (the "GPL License"), a copy of which is
#	available along with the File in the license.txt file or by writing to the Free
#	Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 or
#	on the worldwide web at http://www.gnu.org/licenses/gpl.txt.
#	
#	THE FILE IS DISTRIBUTED AS-IS, WITHOUT WARRANTY OF ANY KIND, AND THE IMPLIED
#	WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY
#	DISCLAIMED.  The GPL License provides additional details about this warranty
#	disclaimer.
###################################################################################


from enum import Enum

class CPSS_DXCH_BRG_VLAN_PORT_TAG_CMD_ENT(Enum):
     CPSS_DXCH_BRG_VLAN_PORT_UNTAGGED_CMD_E = 'CPSS_DXCH_BRG_VLAN_PORT_UNTAGGED_CMD_E'
     CPSS_DXCH_BRG_VLAN_PORT_TAG0_CMD_E = 'CPSS_DXCH_BRG_VLAN_PORT_TAG0_CMD_E'
     CPSS_DXCH_BRG_VLAN_PORT_TAG1_CMD_E = 'CPSS_DXCH_BRG_VLAN_PORT_TAG1_CMD_E'
     CPSS_DXCH_BRG_VLAN_PORT_OUTER_TAG0_INNER_TAG1_CMD_E = 'CPSS_DXCH_BRG_VLAN_PORT_OUTER_TAG0_INNER_TAG1_CMD_E'
     CPSS_DXCH_BRG_VLAN_PORT_OUTER_TAG1_INNER_TAG0_CMD_E = 'CPSS_DXCH_BRG_VLAN_PORT_OUTER_TAG1_INNER_TAG0_CMD_E'
     CPSS_DXCH_BRG_VLAN_PORT_PUSH_TAG0_CMD_E = 'CPSS_DXCH_BRG_VLAN_PORT_PUSH_TAG0_CMD_E'
     CPSS_DXCH_BRG_VLAN_PORT_POP_OUTER_TAG_CMD_E = 'CPSS_DXCH_BRG_VLAN_PORT_POP_OUTER_TAG_CMD_E'
     CPSS_DXCH_BRG_VLAN_PORT_DO_NOT_MODIFY_TAG_CMD_E = 'CPSS_DXCH_BRG_VLAN_PORT_DO_NOT_MODIFY_TAG_CMD_E'

class CPSS_DXCH_BRG_FDB_LOOKUP_KEY_MODE_ENT(Enum):
    CPSS_DXCH_BRG_FDB_LOOKUP_KEY_MODE_FID_E = 'CPSS_DXCH_BRG_FDB_LOOKUP_KEY_MODE_FID_E'
    CPSS_DXCH_BRG_FDB_LOOKUP_KEY_MODE_FID_VID1_E = 'CPSS_DXCH_BRG_FDB_LOOKUP_KEY_MODE_FID_VID1_E'

class CPSS_PACKET_CMD_ENT(Enum):
    CPSS_PACKET_CMD_FORWARD_E = 'CPSS_PACKET_CMD_FORWARD_E'
    CPSS_PACKET_CMD_MIRROR_TO_CPU_E = 'CPSS_PACKET_CMD_MIRROR_TO_CPU_E'
    CPSS_PACKET_CMD_TRAP_TO_CPU_E = 'CPSS_PACKET_CMD_TRAP_TO_CPU_E'
    CPSS_PACKET_CMD_DROP_HARD_E = 'CPSS_PACKET_CMD_DROP_HARD_E'
    CPSS_PACKET_CMD_DROP_SOFT_E = 'CPSS_PACKET_CMD_DROP_SOFT_E'
    CPSS_PACKET_CMD_ROUTE_E = 'CPSS_PACKET_CMD_ROUTE_E'
    CPSS_PACKET_CMD_ROUTE_AND_MIRROR_E = 'CPSS_PACKET_CMD_ROUTE_AND_MIRROR_E'
    CPSS_PACKET_CMD_BRIDGE_AND_MIRROR_E = 'CPSS_PACKET_CMD_BRIDGE_AND_MIRROR_E'
    CPSS_PACKET_CMD_BRIDGE_E = 'CPSS_PACKET_CMD_BRIDGE_E'
    CPSS_PACKET_CMD_NONE_E = 'CPSS_PACKET_CMD_NONE_E'
    CPSS_PACKET_CMD_LOOPBACK_E = 'CPSS_PACKET_CMD_LOOPBACK_E'
    CPSS_PACKET_CMD_DEFAULT_ROUTE_ENTRY_E = 'CPSS_PACKET_CMD_DEFAULT_ROUTE_ENTRY_E'

class CPSS_DXCH_BRG_VLAN_FLOOD_VIDX_MODE_ENT(Enum):
    CPSS_DXCH_BRG_VLAN_FLOOD_VIDX_MODE_UNREG_MC_E = 'CPSS_DXCH_BRG_VLAN_FLOOD_VIDX_MODE_UNREG_MC_E'
    CPSS_DXCH_BRG_VLAN_FLOOD_VIDX_MODE_ALL_FLOODED_TRAFFIC_E = 'CPSS_DXCH_BRG_VLAN_FLOOD_VIDX_MODE_ALL_FLOODED_TRAFFIC_E'

class CPSS_DXCH_BRG_VLAN_PORT_ISOLATION_CMD_ENT(Enum):
    CPSS_DXCH_BRG_VLAN_PORT_ISOLATION_DISABLE_CMD_E = 'CPSS_DXCH_BRG_VLAN_PORT_ISOLATION_DISABLE_CMD_E'
    CPSS_DXCH_BRG_VLAN_PORT_ISOLATION_L2_CMD_E = 'CPSS_DXCH_BRG_VLAN_PORT_ISOLATION_L2_CMD_E'
    CPSS_DXCH_BRG_VLAN_PORT_ISOLATION_L3_CMD_E = 'CPSS_DXCH_BRG_VLAN_PORT_ISOLATION_L3_CMD_E'
    CPSS_DXCH_BRG_VLAN_PORT_ISOLATION_L2_L3_CMD_E = 'CPSS_DXCH_BRG_VLAN_PORT_ISOLATION_L2_L3_CMD_E'

class CPSS_DXCH_BRG_VLAN_UNREG_IPM_EVIDX_MODE_ENT(Enum):
    CPSS_DXCH_BRG_VLAN_UNREG_IPM_EVIDX_MODE_BOTH_E = 'CPSS_DXCH_BRG_VLAN_UNREG_IPM_EVIDX_MODE_BOTH_E'
    CPSS_DXCH_BRG_VLAN_UNREG_IPM_EVIDX_MODE_IPV4_E = 'CPSS_DXCH_BRG_VLAN_UNREG_IPM_EVIDX_MODE_IPV4_E'
    CPSS_DXCH_BRG_VLAN_UNREG_IPM_EVIDX_MODE_IPV6_E = 'CPSS_DXCH_BRG_VLAN_UNREG_IPM_EVIDX_MODE_IPV6_E'
    CPSS_DXCH_BRG_VLAN_UNREG_IPM_EVIDX_MODE_BOTH_IPV6_INCREMENT_E = 'CPSS_DXCH_BRG_VLAN_UNREG_IPM_EVIDX_MODE_BOTH_IPV6_INCREMENT_E'

class CPSS_BRG_IPM_MODE_ENT(Enum):
    CPSS_BRG_IPM_SGV_E = 'CPSS_BRG_IPM_SGV_E'
    CPSS_BRG_IPM_GV_E = 'CPSS_BRG_IPM_GV_E'

class CPSS_IP_SITE_ID_ENT(Enum):
    CPSS_IP_SITE_ID_INTERNAL_E = 'CPSS_IP_SITE_ID_INTERNAL_E'
    CPSS_IP_SITE_ID_EXTERNAL_E = 'CPSS_IP_SITE_ID_EXTERNAL_E'

class CPSS_DXCH_BRG_IP_CTRL_TYPE_ENT(Enum):
    CPSS_DXCH_BRG_IP_CTRL_NONE_E = 'CPSS_DXCH_BRG_IP_CTRL_NONE_E'
    CPSS_DXCH_BRG_IP_CTRL_IPV4_E = 'CPSS_DXCH_BRG_IP_CTRL_IPV4_E'
    CPSS_DXCH_BRG_IP_CTRL_IPV6_E = 'CPSS_DXCH_BRG_IP_CTRL_IPV6_E'
    CPSS_DXCH_BRG_IP_CTRL_IPV4_IPV6_E = 'CPSS_DXCH_BRG_IP_CTRL_IPV4_IPV6_E'