# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# generated using file ./gen/model/dent/system/os/process.yaml
#
# DONOT EDIT - generated by diligent bots

import pytest
from dent_os_testbed.lib.test_lib_object import TestLibObject
from dent_os_testbed.lib.os.linux.linux_process_impl import LinuxProcessImpl


class Process(TestLibObject):
    """
        Process details by reading /proc/[pid]/status
    """
    async def _run_command(api, *argv, **kwarg):
        devices = kwarg['input_data']
        result = list()
        for device in devices:
            for device_name in device:
                device_result = {
                    device_name : dict()
                }
                # device lookup
                if 'device_obj' in kwarg:
                    device_obj = kwarg.get('device_obj', None)[device_name]
                else:
                    if device_name not in pytest.testbed.devices_dict:
                        device_result[device_name] =  'No matching device '+ device_name
                        result.append(device_result)
                        return result
                    device_obj = pytest.testbed.devices_dict[device_name]
                commands = ''
                if device_obj.os in ['dentos', 'cumulus']:
                    impl_obj = LinuxProcessImpl()
                    for command in device[device_name]:
                        commands += impl_obj.format_command(command=api, params=command)
                        commands += '&& '
                    commands = commands[:-3]

                else:
                    device_result[device_name]['rc'] = -1
                    device_result[device_name]['result'] = 'No matching device OS '+ device_obj.os
                    result.append(device_result)
                    return result
                device_result[device_name]['command'] = commands
                try:
                    rc, output = await device_obj.run_cmd(('sudo ' if device_obj.ssh_conn_params.pssh else '') + commands)
                    device_result[device_name]['rc'] = rc
                    device_result[device_name]['result'] = output
                    if 'parse_output' in kwarg:
                        parse_output = impl_obj.parse_output(command=api, output=output, commands=commands)
                        device_result[device_name]['parsed_output'] = parse_output
                except Exception as e:
                    device_result[device_name]['rc'] = -1
                    device_result[device_name]['result'] = str(e)
                result.append(device_result)
        return result

    async def show(*argv, **kwarg):
        """
        Platforms: ['dentos', 'cumulus']
        Usage:
        Process.show(
            input_data = [{
                # device 1
                'dev1' : [{
                    # command 1
                        'pid':'int',
                }],
            }],
        )
        Description:
        Name:    sshd
        Umask:    0022
        State:    S (sleeping)
        Tgid:    2069
        Ngid:    0
        Pid:    2069
        PPid:    1
        TracerPid:    0
        Uid:    0    0    0    0
        Gid:    0    0    0    0
        FDSize:    64
        Groups:
        NStgid:    2069
        NSpid:    2069
        NSpgid:    2069
        NSsid:    2069
        VmPeak:       76124 kB
        VmSize:       76120 kB
        VmLck:           0 kB
        VmPin:           0 kB
        VmHWM:        2972 kB
        VmRSS:        2972 kB

        """
        return await Process._run_command('show', *argv, **kwarg)
