- module: base
  description: |
    This will be the top most module from which all the subsystems hang off
  classes:
  - name: base
    singleton: True
    desc: |
      Base class for all the other classes.
    members:
    - name: attributes
      cls: "dent:base:attributes"
      desc: |
        this holds all the attributes at the top level, this will be a place
        holder class for arbitraty data.
    - name: duts
      cls: "dent:base:duts"
      desc: |
        This represents the operational and other state of the Device Under Test(DUT)
    - name: infrastructure
      cls: "dent:base:infrastructure"
      desc: |
        This holds all the infrastructure related information
    - name: network
      cls: "dent:testbed:testbed_network"
      desc: |
        This holds all the networl related information for the Testbed.
    - name: traffic_genertors
      cls: "dent:traffic:traffic_generators"
      desc: |
        List of Traffic generators
  - name: attributes
    singleton: True
    desc: |
      Place holder for arbitrary data.
  - name: duts
    members:
    - name: device_id
      type: str
      desc: |
        Device idendentification
    - name: platform
      cls: "dent:platform:platform"
      desc: |
        Platform related information like sensors, cpld, drivers etc.
    - name: network
      cls: "dent:network:device_network"
      desc: |
        Contains all the network related information L1,L2,L3 etc
    - name: system
      cls: "dent:system:device_system"
      desc: |
        Contains system related information related to Operating system and other entities
  - name: infrastructure
    members:
    - name: device_id
      type: str
      desc: |
        Device idendentification
    - name: network
      cls: "dent:network:device_network"
      desc: |
        Contains all the network related information L1,L2,L3 etc
