name: Linters

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker run -v $PWD:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest --ignore=minutes --disable=MD013 "**/*.md"

  lint-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        recursive: true
        verbose: true
        config: .github/configs/.hadolint.yaml

  lint-shell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azohra/shell-linter@v0.6.0

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ibiqlik/action-yamllint@v3
      with:
        config_data: "{extends: default, rules: {line-length: disable, indentation: disable}}"
