name: Spellcheck
on:
  pull_request:
    paths:
    - '**/*.md'
    - '.github/configs/.wordlist.txt'
  push:
    paths:
    - '**/*.md'
    - '.github/configs/.wordlist.txt'
  workflow_dispatch:

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Spellcheck
      uses: rojopolis/spellcheck-github-actions@0.29.0
      with:
        config_path: .github/configs/.spellcheck.yml # put path to configuration file here
